import {StrictMode, useEffect, useState} from 'react';
import {createRoot} from 'react-dom/client';
import {ScheduleChart, HistoryChart} from './LazyCharts';
import type {State, Entry, Plan, Slot} from './types';
import './style.css';

const screens=['Overview','Schedule','Controller','System','Settings'] as const;
type Screen=typeof screens[number];
const number=(n:number|null|undefined,digits=1)=>n==null?'Unavailable':n.toLocaleString(undefined,{maximumFractionDigits:digits});
const bytes=(n:number|undefined)=>n==null?'Unavailable':n<1048576?`${number(n/1024,1)} KiB`:n>1073741824?`${number(n/1073741824,2)} GiB`:`${number(n/1048576,1)} MiB`;
const stamp=(s:string|null|undefined,zone?:string)=>s?new Intl.DateTimeFormat(undefined,{dateStyle:'medium',timeStyle:'short',timeZone:zone}).format(new Date(s)):'Not sampled';
const route=()=>screens.find(s=>s.toLowerCase()===location.hash.slice(1))||'Overview';
function Metric({label,value,note}:{label:string;value:string;note?:string}){return <div className="metric"><p>{label}</p><strong>{value}</strong>{note&&<small>{note}</small>}</div>;}
function Card({title,children,description}:{title:string;children:React.ReactNode;description?:string}){return <section className="card"><h2>{title}</h2>{description&&<p className="muted">{description}</p>}{children}</section>;}
function HA({href,children}:{href:string;children:React.ReactNode}){return <a className="button" href={href} target="_top">{children}</a>;}
function Json({value}:{value:unknown}){return <pre>{JSON.stringify(value,null,2)}</pre>;}
function Command({value}:{value:unknown}) {
  if(!value||typeof value!=='object')return <span>Unavailable</span>;
  return <dl className="command">{Object.entries(value).filter(([key])=>key!=='schema_version').map(([key,v])=><div key={key}><dt>{key.replaceAll('_',' ')}</dt><dd>{typeof v==='boolean'?(v?'Yes':'No'):typeof v==='object'?JSON.stringify(v):String(v).replaceAll('_',' ')}</dd></div>)}</dl>;
}

function Schedule({plan,dark}:{plan:Plan;dark:boolean}) {
  const [source,setSource]=useState<'household'|'execution'>('household');
  const slots=(source==='execution'?plan.execution:plan.household)||[];
  const [selected,setSelected]=useState(0);
  const [table,setTable]=useState(false);
  const index=Math.min(selected,Math.max(slots.length-1,0));
  const slot:Slot|undefined=slots[index];
  return <>
    <div className="toolbar"><div><label htmlFor="plan-scope">Forecast scope</label><select id="plan-scope" value={source} onChange={e=>{setSource(e.target.value as typeof source);setSelected(0);}}><option value="household">Whole household</option>{plan.execution&&<option value="execution">Execution plan</option>}</select></div><button aria-pressed={table} onClick={()=>setTable(!table)}>{table?'Show charts':'Show data table'}</button></div>
    <div className="plan-caption"><span>Plan <code>{plan.plan_id}</code></span><span>Issued {stamp(plan.issued_at,plan.timezone)}</span><span>{plan.timezone}</span></div>
    <Card title="Your energy schedule" description="Forecasts throughout the horizon. Elapsed forecast intervals are not measurements. Inspect any interval below; use the range handles to zoom.">
      {table?<div className="table-wrap"><table><caption>Forecast intervals · {plan.timezone}</caption><thead><tr><th>Time</th><th>Prices</th><th>Buy / kWh</th><th>House kW</th><th>Battery %</th></tr></thead><tbody>{slots.map((s,i)=><tr key={s.start}><td><button className="text-button" onClick={()=>setSelected(i)}>{stamp(s.start,plan.timezone)}</button></td><td>{s.binding?'Published':'Estimated'}</td><td>{number(s.shadow_import_sek_per_kwh,3)}</td><td>{number(s.load_w===null?null:s.load_w/1000,2)}</td><td>{number(s.battery_soc===null?null:s.battery_soc*100)}</td></tr>)}</tbody></table></div>:<ScheduleChart slots={slots} plan={plan} dark={dark} onSelect={setSelected}/>}
    </Card>
    {slot&&<Card title="Interval inspector" description="Planner intent only. Requests do not prove device operation or delivered energy.">
      <div className="toolbar"><button disabled={index===0} onClick={()=>setSelected(index-1)}>← Previous</button><label className="interval-label">Selected interval<select value={index} onChange={e=>setSelected(Number(e.target.value))}>{slots.map((s,i)=><option key={s.start} value={i}>{stamp(s.start,plan.timezone)}</option>)}</select></label><button disabled={index===slots.length-1} onClick={()=>setSelected(index+1)}>Next →</button></div>
      <div aria-live="polite" className="metrics compact"><Metric label="Price source" value={slot.binding?'Published':'Estimated'}/><Metric label="Buy / sell per kWh" value={`${number(slot.shadow_import_sek_per_kwh,3)} / ${number(slot.shadow_export_sek_per_kwh,3)}`} note={plan.currency}/><Metric label="Expected demand" value={`${number(slot.load_w===null?null:slot.load_w/1000,2)} kW`}/></div>
      <div className="table-wrap"><table><caption>Planned device actions</caption><thead><tr><th>Device</th><th>Planned request</th></tr></thead><tbody>{Object.entries(slot.device_commands||{}).map(([key,command])=><tr key={key}><td>{plan.devices.find(d=>d.key===key)?.name||key}</td><td><Command value={command}/></td></tr>)}{slot.battery_command!=null&&<tr><td>House battery</td><td><Command value={slot.battery_command}/></td></tr>}</tbody></table></div>
    </Card>}
  </>;
}

function Setup({state}:{state:State}) {return <Card title="Connect your Home Assistant integration" description="The app is running. Connect the bundled companion to see your home’s live schedule and controller information."><ol className="steps"><li>Open this app’s Configuration in Home Assistant.</li><li>Enable <strong>Install companion</strong>, save, and restart the SHS app.</li><li>Check the installation result here, then restart Home Assistant Core.</li><li>Turn off Install companion after the version check succeeds.</li></ol><p>The matching integration version is <strong>{state.required_companion}</strong>. Your existing integration settings, history and device control stay in Home Assistant.</p><p className={state.companion.state==='failed'?'error':'muted'}>{state.companion.message}</p><HA href={state.app_slug?`/hassio/addon/${state.app_slug}/config`:'/hassio/dashboard'}>Open app settings</HA><span className="link-gap"/><HA href="/config/integrations/integration/shs_energy">Open SHS integration</HA></Card>;}

function App() {
  const [state,setState]=useState<State|null>(null),[error,setError]=useState(''),[screen,setScreen]=useState<Screen>(route),[entryId,setEntryId]=useState('');
  const [theme,setTheme]=useState(()=>localStorage.getItem('shs-theme')||'system');
  const [systemDark,setSystemDark]=useState(matchMedia('(prefers-color-scheme: dark)').matches);
  const dark=theme==='dark'||(theme==='system'&&systemDark);
  useEffect(()=>{document.documentElement.dataset.theme=dark?'dark':'light';},[dark]);
  useEffect(()=>{const media=matchMedia('(prefers-color-scheme: dark)');const change=()=>setSystemDark(media.matches);media.addEventListener('change',change);return()=>media.removeEventListener('change',change);},[]);
  useEffect(()=>{const change=()=>setScreen(route());window.addEventListener('hashchange',change);return()=>window.removeEventListener('hashchange',change);},[]);
  useEffect(()=>{
    const controller=new AbortController();let active=true;
    async function update(){if(document.hidden)return;try{const response=await fetch('./api/state',{signal:controller.signal,cache:'no-store'});if(!response.ok)throw new Error(`App request failed (${response.status})`);const next:State=await response.json();if(active){setState(next);setError('');}}catch(e){if(active)setError(e instanceof Error?e.message:'App connection lost');}}
    void update();const interval=setInterval(update,15000);document.addEventListener('visibilitychange',update);return()=>{active=false;controller.abort();clearInterval(interval);document.removeEventListener('visibilitychange',update);};
  },[]);
  const entry:Entry|undefined=state?.snapshot?.entries.find(e=>e.id===entryId)||state?.snapshot?.entries[0];
  const history=state?.system.database?.history||[];
  const appLink=state?.app_slug?`/hassio/addon/${state.app_slug}/info`:'/hassio/dashboard';
  const connected=state?.connection.state==='connected'&&!error;
  return <><a className="skip" href="#content">Skip to content</a><header><div className="brand"><img src="./shs.png" alt="" width="48" height="48"/><div><strong>Smart Home Solutions</strong><span>Energy, working together.</span></div></div><div className="connection"><span className={`dot ${connected?'good':''}`}/>{connected?'Connected':'Awaiting connection'}</div></header>
    <nav aria-label="Main navigation">{screens.map(s=><a key={s} href={'#'+s.toLowerCase()} aria-current={screen===s?'page':undefined}>{s}</a>)}</nav>
    <main id="content"><div className="page-heading"><div><p className="eyebrow">SHS ENERGY</p><h1>{screen==='Overview'?'A clearer view of your energy':screen}</h1><p className="muted">{screen==='Overview'?'Your plan, your home, and what is happening right now.':screen==='Schedule'?'Follow the plan from price to power.':screen==='Controller'?'See what was planned, requested and measured.':screen==='System'?'Understand the app’s health and resource use.':'Make SHS feel at home.'}</p></div>{state?.snapshot&&state.snapshot.entries.length>1&&<label>Home<select value={entry?.id} onChange={e=>setEntryId(e.target.value)}>{state.snapshot.entries.map(e=><option key={e.id} value={e.id}>{e.title}</option>)}</select></label>}</div>
    {error&&<div className="notice error" role="alert">{error}. Displayed values are from the last successful update.</div>}
    {state&&state.connection.state!=='connected'&&<div className="notice" role="status"><strong>{state.connection.state==='incompatible'?'Companion update required':'Home Assistant connection'}</strong><p>{state.connection.message}</p>{state.snapshot&&<p>Retained snapshot: {stamp(state.snapshot.sampled_at)}. Values are stale.</p>}</div>}
    {!state?<Card title="Opening your energy dashboard"><p role="status">Connecting to the SHS app…</p></Card>:<>
      {(screen==='Overview'||screen==='Schedule'||screen==='Controller')&&!entry&&<Setup state={state}/>}
      {entry&&entry.state!=='loaded'&&<Card title="Integration is not loaded"><p>Home Assistant reports: {entry.state}.</p><HA href="/config/integrations/integration/shs_energy">Inspect integration</HA></Card>}
      {entry?.attention&&entry.attention.length>0&&screen!=='System'&&screen!=='Settings'&&<section className="notice"><h2>Needs attention</h2>{entry.attention.map((item,i)=><div className="issue" key={i}><strong>{item.title||'Integration issue'}</strong><p>{item.detail}</p>{item.items?.map((text,j)=><p key={j}>{text}</p>)}<p>{item.next_step}</p>{item.fix?.fields?.map(field=><p key={field.url}><HA href={field.url}>{field.message||`Fix ${field.key.replaceAll('_',' ')}`}</HA></p>)}</div>)}</section>}
      {screen==='Overview'&&entry?.state==='loaded'&&<>
        <div className="metrics">{[['House demand','house'],['Solar production','solar'],['Grid · import + / export −','grid'],['Battery state of charge','battery_soc']].map(([label,key])=>{const m=entry.measurements?.[key];return <Metric key={key} label={label} value={m?.value==null?'Unavailable':`${number(m.value/(m.unit==='W'?1000:1),2)} ${m.unit==='W'?'kW':m.unit}`} note={m?.observed_at?`Observed ${stamp(m.observed_at)}`:'No valid source reading'}/>;})}</div>
        <div className="two-columns"><Card title="The current plan"><span className="badge">{entry.operation?.label||entry.operation?.state||'Unavailable'}</span><p>{entry.operation?.reason}</p>{entry.schedule&&<p className="muted">Issued {stamp(entry.schedule.issued_at,entry.schedule.timezone)}<br/>Valid until {stamp(entry.schedule.valid_until,entry.schedule.timezone)}</p>}<a className="button primary" href="#schedule">Explore your schedule →</a></Card><Card title="Control stays with your integration"><p>The Home Assistant integration is the sole device controller in this release. The app observes its decisions and measurements.</p><p className="muted">No device permissions or historical data were moved on installation.</p><a className="button" href="#controller">Inspect controller activity</a></Card></div>
        <Card title="Plan and measurement" description="One-minute observations collected since app installation. The forecast is captured at the same time as each measurement, not reconstructed from today’s plan."><HistoryChart history={history} entryId={entry.id} dark={dark}/></Card>
      </>}
      {screen==='Schedule'&&entry?.state==='loaded'&&(entry.schedule?<Schedule key={entry.schedule.plan_id+entry.schedule.issued_at} plan={entry.schedule} dark={dark}/>:<Card title="No displayable schedule"><p>{entry.operation?.reason||'Waiting for a validated plan.'}</p><HA href={`/shs-energy?config_entry=${encodeURIComponent(entry.id)}`}>Open integration</HA></Card>)}
      {screen==='Controller'&&entry?.state==='loaded'&&<><Card title="Planned and measured demand" description="Power samples, not delivered-energy accounting. Missing readings remain gaps. These observations cover the most recent four hours retained for display."><HistoryChart history={history} entryId={entry.id} dark={dark}/><details><summary>Inspect sampled values</summary><div className="table-wrap"><table><thead><tr><th>Sampled</th><th>Measured W</th><th>Planned W</th><th>Plan</th></tr></thead><tbody>{history.map(h=><tr key={h.sampled_at}><td>{stamp(h.sampled_at)}</td><td>{number(h.telemetry?.[entry.id]?.measured_w)}</td><td>{number(h.telemetry?.[entry.id]?.planned_w)}</td><td>{h.telemetry?.[entry.id]?.plan_id||'Unavailable'}</td></tr>)}</tbody></table></div></details></Card><Card title="Latest controller decisions" description="These are integration reports. A request or service acknowledgement does not prove delivered power. Verification results are hypothetical.">{Object.entries(entry.controllers||{}).map(([key,value])=><div className="controller-row" key={key}><div><h3>{key.replaceAll('_',' ')}</h3><span className="badge">{value.state}</span></div><p>{value.reason||'No explanatory reason recorded.'}</p><details><summary>Inspect recorded evidence</summary><Json value={value}/></details></div>)}</Card></>}
      {screen==='System'&&<><div className="metrics"><Metric label="Container CPU" value={state.system.resources?`${number(state.system.resources.cpu_percent)}%`:'Unavailable'} note="Supervisor CPU normalization"/><Metric label="Container memory" value={bytes(state.system.resources?.memory_usage)} note={state.system.resources?`Limit ${bytes(state.system.resources.memory_limit)}`:''}/><Metric label="App database" value={bytes(state.system.database?.file_bytes)} note="Does not include HA integration history"/><Metric label="Shared filesystem free" value={bytes(state.system.filesystem_free_bytes)} note="Space available on the /data filesystem"/></div>{state.system.error&&<p className="notice error">{state.system.error}</p>}<Card title="Container resources" description={`Sampled ${stamp(state.system.sampled_at)}. One-minute sampling; seven-day retention; latest four hours shown.`}><HistoryChart history={history} resources dark={dark}/><div className="metrics compact"><Metric label="Disk read / written" value={`${bytes(state.system.resources?.blk_read)} / ${bytes(state.system.resources?.blk_write)}`} note="Cumulative container I/O counters"/><Metric label="Network received / sent" value={`${bytes(state.system.resources?.network_rx)} / ${bytes(state.system.resources?.network_tx)}`} note="Counters reset when the container restarts"/></div></Card>{state.system.database&&<Card title="Database inspection" description={`SQLite schema ${state.system.database.schema_version} · ${state.system.database.journal_mode} journal · ${state.system.database.page_size}-byte pages · ${state.system.database.free_pages} free pages. Sizes measured using dbstat.`}><div className="table-wrap"><table><thead><tr><th>Table</th><th>Rows</th><th>Allocated pages</th><th>Size</th></tr></thead><tbody>{state.system.database.tables.map(t=><tr key={t.name}><td>{t.name}</td><td>{number(t.rows,0)}</td><td>{t.pages}</td><td>{bytes(t.bytes)}</td></tr>)}</tbody></table></div><h3>Query performance</h3><p className="muted">Application timings include execution, fetch and commit. Queue time is the app’s database lock wait, not SQLite’s internal lock wait. Recent maxima cover 120 operations.</p><div className="table-wrap"><table><thead><tr><th>Operation</th><th>Count</th><th>Errors</th><th>Last ms</th><th>Recent max ms</th><th>Queue ms</th></tr></thead><tbody>{state.system.database.operations.map(op=><tr key={op.name}><td>{op.name}</td><td>{op.count}</td><td>{op.errors}</td><td>{number(op.last_ms,2)}</td><td>{number(op.max_recent_ms,2)}</td><td>{number(op.queue_ms,2)}</td></tr>)}</tbody></table></div><details><summary>History query plan</summary><Json value={state.system.database.query_plan}/></details></Card>}</>}
      {screen==='Settings'&&<><div className="two-columns"><Card title="Appearance"><label htmlFor="theme">Color theme</label><select id="theme" value={theme} onChange={e=>{setTheme(e.target.value);localStorage.setItem('shs-theme',e.target.value);}}><option value="system">Follow system</option><option value="light">Light</option><option value="dark">Dark</option></select><h3>SHS in your sidebar</h3><p>{state.sidebar_enabled===null?'Use Home Assistant’s Show in sidebar switch.':`Currently ${state.sidebar_enabled?'shown':'hidden'} in the Home Assistant sidebar.`}</p><HA href={appLink}>Manage sidebar visibility</HA><p className="muted">Home Assistant owns this setting. SHS uses the integration’s existing home-and-energy sidebar icon.</p></Card><Card title="Versions and compatibility"><dl><dt>SHS app</dt><dd>{state.app_version}</dd><dt>Bundled companion</dt><dd>{state.required_companion}</dd><dt>Loaded companion</dt><dd>{state.snapshot?.integration_version||state.connection.loaded_version||'Not connected'}</dd><dt>Bridge protocol</dt><dd>{state.protocol}</dd><dt>Control owner</dt><dd>{state.control_owner}</dd></dl><p>Only the bundled companion version is accepted. A mismatch stops live dashboard updates.</p></Card></div><Setup state={state}/><Card title="Configuration and migration"><p>Edit device bindings, planning preferences and control permissions in the existing integration. The app does not grant control.</p><HA href={entry?`/shs-energy?config_entry=${encodeURIComponent(entry.id)}`:'/config/integrations/integration/shs_energy'}>Open SHS configuration</HA><h3>Migration has not started</h3><p>This first app release leaves integration databases and runtime ownership in Home Assistant. The one-off transfer and controller handover are a separate, verified migration step after the HAOS installation check.</p></Card></>}
      <footer><span>SHS Energy · {state.app_version}</span><span>Home snapshot {stamp(state.snapshot?.sampled_at)}</span></footer>
    </>}
    </main></>;
}
createRoot(document.getElementById('root')!).render(<StrictMode><App/></StrictMode>);
