name: SHS Energy
version: 0.1.0-beta.42
slug: shs_energy
description: Your energy plan, controller insights and system diagnostics
url: https://github.com/SHS-se/shs-ha-integration/tree/main/apps/shs_energy
arch:
  - aarch64
  - amd64
image: ghcr.io/shs-se/shs-energy-app
startup: application
boot: auto
init: false
ingress: true
ingress_port: 8099
panel_title: SHS
panel_icon: mdi:home-lightning-bolt
panel_admin: true
homeassistant_api: true
map:
  - type: homeassistant_config
    read_only: false
    path: /homeassistant
options:
  install_companion: false
  log_level: info
schema:
  install_companion: bool
  log_level: list(debug|info|warning|error|critical)?
